[project]
name = "social-network"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aioboto3>=15.5.0",
    "aiosqlite>=0.22.1",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.136.3",
    "fastcrud>=0.22.3",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.14.1",
    "pyjwt[crypto]>=2.13.0",
    "redis>=8.1.0",
    "sqladmin[full]>=0.31.1",
    "sqlalchemy>=2.0.50",
    "structlog>=26.1.0",
]

[dependency-groups]
dev = [
    "faker>=40.23.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.15.17",
]

[tool.ruff]
target-version = "py314"
line-length = 88
exclude = [
    ".git",
    "__pycache__",
    "migrations",
    "venv",
    ".venv",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "UP",
]
ignore = ["E501"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope="session"
testpaths = ["tests"]

addopts = [
    "-v",
]

[tool.fastapi]
entrypoint = "src.main:app"
