"""add chat member

Revision ID: bea909c2b716
Revises: 5ae8613a9803
Create Date: 2026-09-05 20:37:41.967788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bea909c2b716"
down_revision: str | Sequence[str] | None = "5ae8613a9803"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_members",
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", name="chatrole"), nullable=False
        ),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
            name=op.f("fk_chat_members_chat_id_chats"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_members")),
        sa.UniqueConstraint("chat_id", "user_id", name="uq_chat_members_chat_user"),
    )
    with op.batch_alter_table("chat_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_members_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sender_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_messages_sender_id"), ["sender_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_messages_sender_id_chat_members"),
            "chat_members",
            ["sender_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_messages_sender_id_chat_members"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_messages_sender_id"))
        batch_op.drop_column("sender_id")

    with op.batch_alter_table("chat_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_members_user_id"))

    op.drop_table("chat_members")
    # ### end Alembic commands ###
